### ISSUE TITLE
[Documentation request] Update repo to reflect "queue" replacing "cancellationToken"

### ISSUE THREAD

**Issue by EFinley** [jamesmontemagno/TextToSpeechPlugin#15]
Obviously you're hard at work on this one!  Good timing, by me; it's an excellent fit for my project.

But Intellisense is leaving me rather puzzled, because the method signature it has for Speak() isn't the same as the method signature for the version you've got up here in /src.

I'm trying to write a wrapper for your code which will let me integrate its timings with the rest of the app, so the question of how I access cancellations is of interest to me.  And I can work with either - but I gotta have the information on what's up!  The docstring is (IMO) not as helpful as it could be... do you mean "True if you want to chain them together, false if you want the new one to cancel the current one"?

Does that imply that you're unifying Task and non-Task cancellation options into that simple boolean?  Not a bad idea, although in that case a convenience function of "TTS.StopSpeaking" which cancels without starting a fresh one (possibly with the use of [playSilentUtterance](https://developer.android.com/reference/android/speech/tts/TextToSpeech.html#playSilentUtterance(long,%20int,%20java.lang.String)), at least on that platform) might be a nice feature to at least pencil in.

(Currently I'm restricted to Android-only but I'm trying to use as many cross-platform components as possible.  Amusingly, I arrived at your TTS and Rendy Del Rosario's _Device Motion_ via entirely separate search paths.  Both are lovely!)

Cheers,
- Eric F.

**Comment by jamesmontemagno** [comment]
We are currently working on 3.0 and will document it when it is all done, you should not use this code just yet as it is under development still. I will work on the documentation too in the xml comments

For 2.0 reference check here: https://github.com/jamesmontemagno/TextToSpeechPlugin/tree/release-2.0.0

**Comment by EFinley** [comment]
I see where you're going with the 3.0 code compared to the 2.0 version, and mostly it looks good.

_How_ would someone cause issues with your lock by using the queueing mechanism?  Are you anticipating a single app using both the 2.0 _and_ 3.0 methods to access the queue / the tcs?  Or are you talking about how to support the equivalent functionality to the QUEUE_FLUSH flag in the original, since awaiting intrinsically functions as if they were putting them on the end of the queue?

**Comment by jamesmontemagno** [comment]
So the idea here would be that you can pass in a cancelation token. This cancelation token can be canceled which will stop the text to speech:

For instance:

```
cancelToken?.Register(() =>
            {
                textToSpeech.Stop();
                tcs.TrySetCanceled();
            });
```

Now for queued speak back you would want to do something like:

```
var current = CrossTextToSpeech.Current;
await current.Speak("First");
await current.Speak("Second");
```

**Comment by EFinley** [comment]
Yeah.  And the desired behaviour would be that you have these options:
- Invoke the second one (possibly from another thread) as something like `await current.Speak("Second", interrupt: true)` and have it use the token on the first one so as to produce the interruption.
- Invoke `cancelToken.Cancel( )` from external code, and have it interrupt the queued utterances to which we provided the same token.  Presumably not cancelling those to which we didn't.

To get that first behaviour, I would say that we should make sure there's always a cancellation token, internally supplied (and local to the utterance) if not provided - IIRC there already is, it's just kept as a local variable inside the `Speak( )` call.  Keep the currently-being-uttered cancellation token as a TTS-instance-level variable (or link it to a TTS-instance-level tcs).  Possibly a Queue or linked-list of tcs'es, but that might not actually be necessary.

Something like:

```
struct CancelPacket
{
    TaskCompletionSource tcs;
    cancellationTokenSource ctSource;
    CancelPacket( cancellationToken? externalToken )
    {
        tcs = new TaskCompletionSource( );
        ctSource = CreateLinkedTokenSource( new[ ] {externalToken ?? cancellationToken.None} );
        ctSource.token.Register(( ) => // As you described above
    }
}

public CancelPacket currentUtterance;

public Task Speak (params yadda yadda)
{
    CancelPacket thisUtterancePacket = new CancelPacket ( cancelToken );

    CancelPacket whatAreWeWaitingFor;
    lock ( syncLock ) // Effectively used as an "InterlockedCompareExchange" for our structs
    {
        whatAreWeWaitingFor = this.currentUtterance;
        this.currentUtterance = thisUtterancePacket;
    }

    if ( interrupt ) whatAreWeWaitingFor.ctSource.Cancel( );
    await whatAreWeWaitingFor.tcs.Task;

    // Proceed...
}
```

That look about right?

I think in order to support both of the behaviours in my bulleted list at the start, we really do need two separate parameters, one to denote queueing behaviour and one to tie the speech to any external cancellations.

**Comment by EFinley** [comment]
Quick question (if you see this)... where is the 3.0 update right now?  I'm at the point where one small detail, the inability to retrieve the task representing the utterance completion (in 2.0.x), is biting me.  But if 3.0 is at all functional, then that would solve the problem right there.  (And, man, have I ever done a lot of other work with Tasks and cancellation tokens since this thread in November!)
