### ISSUE TITLE
[Feature Request]  Allow getVoices( ) and setVoice( ) on Android

### ISSUE THREAD

**Issue by EFinley** [jamesmontemagno/TextToSpeechPlugin#16]
The title is fairly self-explanatory, I think.  Eventually I want to be able to use alternate voices, and while it _looks_ like I might be able to sneak it in through the existing `crossLocale` parameter (given the Android [docs](https://developer.android.com/reference/android/speech/tts/TextToSpeechService.html), assuming API 20+), I'd have to wrangle with it a bit to get there.

Would there be interest if I forked out a branch to try implementing that myself?
- Eric F.

**Comment by jamesmontemagno** [comment]
Unfortunately Get/Set Voices is completely broken as I tried to use it a long time ago and have been tracking: https://code.google.com/p/android/issues/detail?id=80696

**Comment by jamesmontemagno** [comment]
The locale is the only thing that I know works and can support really.

**Comment by EFinley** [comment]
Huh.  Well, fair enough; if it rises enough in importance to me, I may see if I can make something work.

(Offhand, I think I'd start by putting a wrapper around TextToSpeech.DefaultEngine - strangely, an instance property - which intercepts calls to onGetVoices and possibly onGetLanguageFeatures, as suggested in that issue's thread, and serves them up properly.  That or maybe just a wrapper around defaultVoice and/or the user's selected Voice, which serves up something serializable instead of null when asked about its features.  I shall think on this.)

**Comment by EFinley** [comment]
Come to that, if the only problem is an exception being thrown when getVoices( ) is querying an engine that doesn't support voices, well, catch the exception and return - by definition - an empty list of voices.

**Comment by jamesmontemagno** [comment]
Yeah, i will re-try it again against the latest API to see if there is some sorta work around for it :)

Essentially I convert it to CrossLocale and then set it via that.
