### ISSUE TITLE
[Feature Request / Platform Balancing]  StackOverflow link for setting speech volume on Android

### ISSUE THREAD

**Issue by EFinley** [jamesmontemagno/TextToSpeechPlugin#17]
With a little work, it might be possible to remove the "WP/iOS only" caveat that's currently on the `volume` parameter.  Check out [this answer on SO](http://stackoverflow.com/a/7558952) for what looks like a pretty solid solution.  Bonus points if we can combine it with [KEY_PARAM_STREAM](https://developer.android.com/reference/android/speech/tts/TextToSpeech.Engine.html#KEY_PARAM_STREAM) in the constructor...

**Comment by jamesmontemagno** [comment]
Implemented in 3.3.0
