### ISSUE TITLE
[Feature Request] Cancel speech

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/TextToSpeechPlugin#2]
Copied from: https://github.com/jamesmontemagno/Xamarin.Plugins/issues/38
## Feature Request:

Method to stop the Text To Speech after it has started.

**Comment by jamesmontemagno** [comment]
@aritchie I am adding this to v3 as I think it would be a nice addition and all the version support it :)

Even though technically the cancellation token will handle some of this, but people may not await on it so we can cancel it on each platform.

**Comment by aritchie** [comment]
This will cancel the current speech, but not everything else that make be in the "await" queue.

**Comment by aritchie** [comment]
What I mean by this is:
await TTS("first tts");
await TTS("second tts");
Cancel();  // may cancel the first tts, but not the second.

**Comment by jamesmontemagno** [comment]
Yeah... I was thinking something like this:

```
var task1 = TTS("first tts");
//do stuff

await task1;
var task2 = TTS("second tts");

//user presses cancel
Cancel(); //cancels second one because we waited #1
```

**Comment by jamesmontemagno** [comment]
Also... if I do:

```
await TTS("1");
await TTS("2");
```

I assume that these will block my UI thread at this point since they are now task based? So, the usage really may be:
//use case 1:

```
TTS("first tts"); // fire and forget
```

//use case 2... will this crash since it is on the background?:

```
Task.Run(()=>
{
  await TTS("hello");
  await TTS("Hello 2");
});
```

probably more realistic....

```
TTS("hello world").ContinueWith(()=>TTS("Now say this"));
```

**Comment by aritchie** [comment]
All of your listed use cases will pass.  The issue with a global cancel function is that you won't know what you're cancelling.  I think we can whip something up as a cancellall function though
