### ISSUE TITLE
Crosslocale doesn't seem to be working

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/TextToSpeechPlugin#22]
Version Number of Plugin: 2.0.0
Device Tested On: Sony Experia z3 android 6.0.1
 
 I tried to set as below and tested with german and spanish languages but everytime, I get English accent. I compared language and displayname from the avilable list and they are set correctly for both languages.
I expect native speech. Do I understand this wrong? Do i do something wrong?

```
  var crosslocale = new Plugin.TextToSpeech.Abstractions.CrossLocale()
            {
                 Language = CurrentCultureInfo.TwoLetterISOLanguageName,
                  DisplayName = CurrentCultureInfo.DisplayName,
                   
            };

 Plugin.TextToSpeech.CrossTextToSpeech.Current.Speak(text, crossLocale: crosslocale)
```

**Comment by jamesmontemagno** [comment]
You can't create your own, you need to query the system for them and then use one of them that is returned.

**Comment by jamesmontemagno** [comment]
Use: GetInstalledLanguages()

**Comment by EmilAlipiev** [comment]
thanks, that works :)
