### ISSUE TITLE
[Help Needed and Feature Request] Choosing the speech engine and locale

### ISSUE THREAD

**Issue by SaikyoKid** [jamesmontemagno/TextToSpeechPlugin#23]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Feature Request:
I don't know if this can be done or not. If it can be done, please guide me.
But, it would be nice to be able to choose the Speech Engine and a locale of our choice.

I found that locale can be set, but I couldn't get it working. I wanted to set "en_IN" as the locale to be used. how do I do that?

**Comment by jamesmontemagno** [comment]
You must query: GetInstalledLanguages and then pass one of the Cross Locales in from it

**Comment by SaikyoKid** [comment]
That's the question.. how do I pass the value? i already got the values of installed languages.
This is my code right now : 

```

Plugin.TextToSpeech.TextToSpeech ttse = new Plugin.TextToSpeech.TextToSpeech();

            CrossLocale localeen;

            localeen.Country = "en_IN";
            localeen.Language = "en_IN";
            ttse.Speak(Text, false, localeen);

```

**Comment by jamesmontemagno** [comment]
You should not be creating the CrossLocale, it must be returned from the method:

```
var items = CrossTextToSpeech.Current.GetInstalledLanguages();
var lang = items[0]; //find your stuff.
CrossTextToSpeect.Current.Speak("Test", false, lang);
```

you should NEVER create an instance of the TextToSpeech Class, you must use the singleton.
