### ISSUE TITLE
Cannot await void on Speak()

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/TextToSpeechPlugin#24]
## Bug 

Version Number of Plugin: 2.0.0
Device Tested On: OnePlus Two
Simulator Tested On: - 

### Expected Behavior
being able to await Speak()

### Actual Behavior

![cantawaitvoid](https://cloud.githubusercontent.com/assets/7255223/24753332/f3c4e172-1ad1-11e7-8ad1-e32ad6e78ce3.png)

### Steps to reproduce the Behavior
Add the plugin version 2.0.0 from nuget
Make an async method and use Speak() like in the getting started:
await CrossTextToSpeech.Current.Speak("Text to speak");

It's really weird, as i can see on the source here on github, that ITextToSpeech Speak() returns a Task, however when i check the code it says void:
![cantawaitvoid2](https://cloud.githubusercontent.com/assets/7255223/24753634/3c954f08-1ad3-11e7-938e-bc487123e547.png)

Any help is appreciated! I might just be failing ;)

**Comment by jamesmontemagno** [comment]
It is in version 3

**Comment by ghost** [comment]
Thanks for the quick answer (20 secs!!!?!?!??!)

- When will you publish version 3?
- Will you rename it to SpeakAsync? ;)

**Comment by jamesmontemagno** [comment]
Eventually 3.0 is in progress.

No plans to re-name.

Docs for 2.0 are here: https://github.com/jamesmontemagno/TextToSpeechPlugin/tree/release-2.0.0
