### ISSUE TITLE
No Arabic text to speech on Android

### ISSUE THREAD

**Issue by alaaabouzeid** [jamesmontemagno/TextToSpeechPlugin#25]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.0.0
Device Tested On: Samsung Galaxy S7 Edge
Simulator Tested On: Visual Studio Emulator for Android, Similar to Samsung Galaxy S5, Sony Experia Z

### Expected Behavior
Should say Arabic words in Text to Speech functionality
### Actual Behavior
Not saying Arabic words. It doesn't say anything, just a very short beep. I haven't tried it on iOS yet so not sure if it works there or not.
### Steps to reproduce the Behavior
I used the following code in a Xamarin.Forms project class:
>Plugin.TextToSpeech.Abstractions.CrossLocale locale = new Plugin.TextToSpeech.Abstractions.CrossLocale(); 
> locale.Language = "ar"; 
> locale.Country = "eg"; 
> Plugin.TextToSpeech.CrossTextToSpeech.Current.Speak("هيا بنا نلعب", false, locale);

Please note that I tried it with and without setting the locale language and country variables.

Thank you very much

**Comment by jamesmontemagno** [comment]
You need to query the language from the system, you can not just specify random codes.

**Comment by alaaabouzeid** [comment]
Yes I tried that but I never get any Arabic languages back. So I was wondering, is this a limitation on Android devices that it doesn't have Arabic TTS?
Thanks.

**Comment by jamesmontemagno** [comment]
Yup, that is correct, the device doesn't have that options. Sometimes you need to download the language packs.

**Comment by alaaabouzeid** [comment]
Thanks for that. Do you know if there is a language pack for Arabic? and if I can include that in the installer package of the app itself? Thanks

**Comment by jamesmontemagno** [comment]
http://www.androidpolice.com/2014/03/05/google-releases-huge-text-to-speech-tts-for-android-update-v3-0-with-high-quality-voices-new-languages-and-ui-changes-apk-download/

**Comment by alaaabouzeid** [comment]
I found this article but unfortunately it still says Arabic is not supported :(
