### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by MaurersMake** [jamesmontemagno/TextToSpeechPlugin#26]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

## Feature Request:
Does this plugin also record speech and convert to text?

**Comment by jamesmontemagno** [comment]
Nope, this one does: https://github.com/aritchie/speechrecognition

**Comment by MaurersMake** [comment]
Will that work in xamarin forms?
