### ISSUE TITLE
[Feature Request] Allow pause between two sentences.

### ISSUE THREAD

**Issue by nbaua** [jamesmontemagno/TextToSpeechPlugin#27]
Hi James,

This is awesome plug-in, really simple and clean.
What I want to request is to allow a variable pause between two phrases.

Use case: I need to implement a read-aloud section (a paragraph of 3-10 lines) with pauses at some place.

What happens right now is, the plug-in reads the para is a somewhat "symmetrical" pattern.
I know there is a **speakRate** option however it is applied uniformly to the entire paragraph

Wouldn't it be nice, if you can come up with a small internal parser which reads some token like **[3S]** or **^2^** which would let the speaker engine pause momentarily.

> For example:
> var LongText = "Dorothy is a young girl who lives with her Aunt Em and Uncle Henry and her little dog Toto on a farm in the Kansas prairies. **^2^** One day, Dorothy and Toto are caught up in a cyclone that deposits her farmhouse into Munchkin Country in the magical Land of Oz. "
> 
> CrossTextToSpeech.Current.Speak(LongText,
> pitch: (float)1.2,
> speakRate: (float)1,
> volume: (float)1.5,
> crossLocale: locale);

as in the above example the speaker engine would wait for 2 seconds before speaking the second sentence.

Hope this is achievable and I am not asking too much. 👍

**Comment by jamesmontemagno** [comment]
In the new beta this is possible. as you could await on them now and add a delay.
