### ISSUE TITLE
Manual Init called in sample

### ISSUE THREAD

**Issue by matthews-jca** [jamesmontemagno/TextToSpeechPlugin#29]
## Bug Information

Version Number of Plugin: 3.0.0
Device Tested On: Android 5.0

### Steps to reproduce the Behavior

Sample applications still call manual CrossLocationsPlugin.Current.Init

### Expected Behavior

If this has been removed, is their anything else that should be done to init? And the samples should be updated

### Code snippet
https://github.com/jamesmontemagno/TextToSpeechPlugin/blob/master/samples/TextToSpeechSample/TextToSpeechSample.Droid/MainActivity.cs

**Comment by jamesmontemagno** [comment]
There is no need for it anymore as I init for you whenever you call anything. I will update the samples. I have been doing so slowly over time.
