### ISSUE TITLE
[Bug] Long text on android fails

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/TextToSpeechPlugin#3]
## Bug

Version Number of Plugin: Latest 2.0.0
Device Tested On: Android
Simulator Tested On: Android
### Expected Behavior

All length of text that is passes 
### Actual Behavior

Fails silently
### Steps to reproduce the Behavior

Send a long string over the limit.

**Comment by jamesmontemagno** [comment]
I am thinking we should expose a new:

public int MaxSpeechLength {get;}

Android docs:
https://developer.android.com/reference/android/speech/tts/TextToSpeech.html#getMaxSpeechInputLength()

Thoughts @aritchie

**Comment by aritchie** [comment]
I've sent some large tts messages that have worked fine.  Curious what the max length is.  As a practice, I plan to submit each sentence or phrease to a separate Speak() call.  

Probably best to document max length and throw an argumentexception when it is too large

**Comment by jamesmontemagno** [comment]
Yeah, could do that and maybe expose it so they know
