### ISSUE TITLE
TextToSpeech Doesn't Work Inside the OnSleep Method inside the App.xaml.cs

### ISSUE THREAD

**Issue by deanilvincent** [jamesmontemagno/TextToSpeechPlugin#32]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: v3.0.1
Device Tested On: Android
Simulator Tested On: Android
Version of VS:  Visual Studio 2017 Community
Version of Xamarin: Lastest
Versions of other things you are using:

### Expected Behavior
The text to speech will work inside the App.xaml.cs OnSleep() method
### Actual Behavior
It doesn't work after I put inside the OnSleep() method
### Code snippet
```
protected override void OnSleep()
{
    // Handle when your app sleeps
    CrossTextToSpeech.Current.Speak("My Text To Speech Sample");    
}
### ScreenShot
none

**Comment by jamesmontemagno** [comment]
Your app isn't open and can't guarantee to work there.
