### ISSUE TITLE
Android crashes when Locale not found. Default as English? 

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/TextToSpeechPlugin#34]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On:  Sony Xperia Z3  Android 6.0.1
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: Latest
Versions of other things you are using: 

### Steps to reproduce the Behavior
If I understand correctly we have to query for selected locale in android as in the given sample

	           ```
             languageButton.Text = selected;

				if (Device.RuntimePlatform == Device.Android)
					locale = locales.FirstOrDefault(l => l.ToString() == selected);
				else
					locale = new CrossLocale { Language = selected };//fine for iOS/WP

```
So in UWP and IOS, it is enough to pass language code.  

### Expected Behavior

Is there a possibility to use have default as English, in any case, if CrossLocales is null or queried CrossLocale  not found. I believe this was behavior in earlier version. 

### Actual Behavior

I had mistake and CrossLocale was returning nothing in Android, application was doing nothing (i didnt event get exception.

**Comment by jamesmontemagno** [comment]
You should never create your own CrossLocale, you should be querying it from the system.
