### ISSUE TITLE
how to get Locales synchronously? Breaking change from version 2 to 3

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/TextToSpeechPlugin#35]
I need to get Locales synchronously because I am running in a method synchronously in following order
 - get locale 
 - do speech
This was working fine in version 2 but in version 3, It returns a task and I dont understand the reason why I cant run it as synchronously , I tried all the possible methods to wait for result but it looks like it doesnt work.  Both below simply should work but when I debug, they dont execute, it seems like getting deadlock. Can you please advise?

`  var crosslocales = Plugin.TextToSpeech.CrossTextToSpeech.Current.GetInstalledLanguages().GetAwaiter().GetResult();`

```
 private static CrossLocale currentLocale;

        public static CrossLocale CurrentLocale
        {
            get
            {
                if (currentLocale.DisplayName == null)
                {
                    getLocale().Wait();
                }

                return currentLocale;
            }
            set { currentLocale = value; }
        }

        private static async Task getLocale()
        {

            var crosslocales = await Plugin.TextToSpeech.CrossTextToSpeech.Current.GetInstalledLanguages();

            if (crosslocales?.Count() > 0)
                currentLocale = crosslocales.Where(c => c.Language == Helpers.Settings.CurrentCultureInfo.TwoLetterISOLanguageName && (c.Language + "-" + c.Country) == Helpers.Settings.CurrentCultureInfo.Name).SingleOrDefault();
        }
```

**Comment by jamesmontemagno** [comment]
Don't call get result, you can't call it from a property, call it form a method or event.
