### ISSUE TITLE
Cancellation Throws exception

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/TextToSpeechPlugin#37]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: Sony Xperia, Samsung S5
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 2.4.x
Versions of other things you are using: 

### Steps to reproduce the Behavior

When I try to cancel using code below; it throws 2 different exception as links below

```
  public CancellationTokenSource cts { get; set; } = new CancellationTokenSource();
        public System.Threading.CancellationToken ct { get; set; } = default(System.Threading.CancellationToken);

ct = cts.Token;

 await Plugin.TextToSpeech.CrossTextToSpeech.Current.Speak(texttospeak, crossLocale: Helpers.Settings.CurrentLocale, cancelToken: ct);

```

calling this OnDisappearing function of the page.
```
 if (ct.CanBeCanceled)
                cts.Cancel();
```

### Actual Behavior

1st exception
https://gist.github.com/EmilAlipiev/c9fa5d63f01b279efb39a0c3ef9963ee
 

2nd exception
https://gist.github.com/EmilAlipiev/b42af633bb7237d0168a8d89d4d980ef

**Comment by aritchie** [comment]
The 1st exception is interesting.  I'll take a look.

The 2nd exception is expected.  When you cancel a task, it will toss out the exception to collapse your await.  You need to manage that exception.
