### ISSUE TITLE
Calling CrossTextToSpeech.Current.Dispose() prevents it from reinitialzing

### ISSUE THREAD

**Issue by nwestfall** [jamesmontemagno/TextToSpeechPlugin#40]
Maybe I'm expecting different behavior, but here is what I came across.  I'm more than happy to fix the bug and create a pull request, but I wanted to make sure I was using it correctly.

## Bug Information

Version Number of Plugin: 3.0.1.0
Device Tested On: Android Device (custom hardware)
Simulator Tested On: N/A
Version of VS: VS 2017
Version of Xamarin: Xamarin.Android projects v8.0.99.67
Versions of other things you are using:

### Steps to reproduce the Behavior
``` c#
CrossTextToSpeech.Current.Dispose();
await CrossTextToSpeech.Current.Speak("Some text");
```

### Expected Behavior
System speaks "Some text"

### Actual Behavior
Error is thrown 

> Exception occured in TTS.Speak for direction text.: Object reference not set to an instance of an object.:   at Plugin.TextToSpeech.TextToSpeech.Speak (System.Nullable`1[T] cancelToken) [0x000b0] in C:\projects\texttospeechplugin\src\TextToSpeech.Plugin.Android\TextToSpeech.cs:150 
11-04 13:14:46.015 E/HockeyApp(16533):   at Plugin.TextToSpeech.TextToSpeech+<Speak>d__11.MoveNext () [0x001ab] in C:\projects\texttospeechplugin\src\TextToSpeech.Plugin.Android\TextToSpeech.cs:91 

### Code snippet
Believe the issue is here where "textToSpeech" is null
https://github.com/jamesmontemagno/TextToSpeechPlugin/blob/b649905adb1c730a12e4bc866a709c384384a061/src/TextToSpeech.Plugin.Android/TextToSpeech.cs#L150

And in dispose it makes "textToSpeech" null, but doesn't set "initalized" back to false
https://github.com/jamesmontemagno/TextToSpeechPlugin/blob/b649905adb1c730a12e4bc866a709c384384a061/src/TextToSpeech.Plugin.Android/TextToSpeech.cs#L274

### Screenshots
N/A

**Comment by jamesmontemagno** [comment]
Don't call: CrossTextToSpeech.Current.Dispose();

Call: CrossTextToSpeech.Dispose();
