### ISSUE TITLE
Crashes sometimes occur in case of cancellation when several requests are pending

### ISSUE THREAD

**Issue by englebertnicolas** [jamesmontemagno/TextToSpeechPlugin#41]
Crashes sometimes occur in case of cancellation when several requests are pending.

Following update corrects the issue:
In the Speak(...) function (TextToSpeech.Plugin.iOS/TextToSpeech.cs line 50), just after:
`await semaphore.WaitAsync(cancelToken);`
Add:
`cancelToken.ThrowIfCancellationRequested();`

(Before calling: `await SpeakUtterance(speechUtterance, cancelToken);`)

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPhone 6 (11.1)
Simulator Tested On: 
Version of VS: 2015 (14.0.25431.01 update 3)
Version of Xamarin: 4.7.10.33
Versions of other things you are using:

**Comment by prashantvc** [comment]
> Crashes sometimes occur in case of cancellation when several requests are pending.

How often does this happen? Could you share crash log? It will help us to troubleshoot the issue
