### ISSUE TITLE
TextToSpeechPlugin Volume not changing

### ISSUE THREAD

**Issue by pollaris** [jamesmontemagno/TextToSpeechPlugin#45]
The following call is executing, but the plugin returns full volume when I set it to zero.

            await CrossTextToSpeech.Current.Speak(s,
                crossLocale: null,
                pitch: 0,
                speakRate: null,
                volume: 0,
                cancelToken: default(CancellationToken));

"s" is a String.  Have I got the syntax right? 

     Plugin version 3.1.1
     Visual Studio 15.5.5
     Tested on Desktop Windows Version 1709
          Lumia Windows 1607
          Acer Windows 1703
          Droid Turbo Android Version 6.0

**Comment by prashantvc** [comment]
Could you add following details to the bug report?
## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

### Expected Behavior

### Actual Behavior

### Code snippet

### Screenshotst

**Comment by jamesmontemagno** [comment]
I have fixed UWP, however as documented the volume has no impact on Android as there is No API to do it.

**Comment by jamesmontemagno** [comment]
I actually got something working now for Android :)

**Comment by pollaris** [comment]
Can you help me correct this Android C# syntax?   The following has the same problem on android.  It plays at full volume even though the volume is set to zero:

            Bundle b = new Bundle();
            b.PutFloat(key: "KEY_PARAM_VOLUME", value: 0);       
            speaker = new TextToSpeech(Android.App.Application.Context, this);               
            speaker.Speak("hello", QueueMode.Flush, b, null);

**Comment by EmilAlipiev** [comment]
on Uwp desktop I am not getting any sound although it says IsSupported=true, is there something special need to be done. it was working before with old version of the package. i updated without code change and it works on android but uwp, no sound.
 I simply do 

` await Plugin.TextToSpeech.CrossTextToSpeech.Current.Speak(textToSpeech, crossLocale: Helpers.Settings.CurrentLocale, cancelToken: ct);`

**Comment by jamesmontemagno** [comment]
@EmilAlipiev good one. fixed it now in 3.2.1

**Comment by pollaris** [comment]
kudos ... the following is working on windows phone and android now:

       await CrossTextToSpeech.Current.Speak(text:s, volume: 0.2f);

**Comment by pollaris** [comment]
You are changing the master volume of the phone, and not restoring it to what it was prior to the call.  I cannot use the plugin as it stands.

**Comment by jamesmontemagno** [comment]
I am setting the Music volume, not the phone volume: am.GetStreamMaxVolume(Stream.Music);


Would also appreciate if you wrote literally anything constructive here at all and not attempt to write in a way that puts down contributors.

What is your "work around" to setting audio and what is the proposed way that you would like for it to work. Android works very different then iOS/Windows as you can't set the volume of the specific stream.

**Comment by pollaris** [comment]
I was hoping your plugin would enable me to adjust the volume the way I do in Android Studio.  Here is the code:

    private TextToSpeech tts;

    public void speakthetext2(String s) {
        final String msg = s;
        tts = new TextToSpeech(getApplicationContext(), new TextToSpeech.OnInitListener() {
            @Override
            public void onInit(int status) {
                if (status != TextToSpeech.ERROR) {
                    Bundle b = new Bundle();
                    b.putFloat(KEY_PARAM_VOLUME, 0.2f);
                    tts.speak(msg, TextToSpeech.QUEUE_ADD, b, "1");
                } else {
                    Toast.makeText(getApplicationContext(), "tts error!", Toast.LENGTH_LONG).show();
                }
            }
        });
    }

I was hoping for a cross plaform plugin that would enable me to adjust the volume as above for the text message being spoken in my app.

**Comment by jamesmontemagno** [comment]
Got it, see that wasn't too hard to explain what you actually wanted it to do and how you were able to accomplish this in java.

So, I have adjust the functionality. If you pass in "null" or don't set the volume it will use the system defaults for whatever the OS decides, which is probably 100%. If you do pass it in then I will set the specific stream's audio on all OS's to use the volume that you pass in.

Since this is a tweak and I need to test a bit more I have a pre-release nuget that you can use: 3.3.0.X-beta

**Comment by EmilAlipiev** [comment]
@jamesmontemagno I am not sure if that is related to what @pollaris is telling but latest stable version restores my phones volume to highest volume when I use it as below without setting any volume parameter. earlier versions didnt have that behavior

`  await Plugin.TextToSpeech.CrossTextToSpeech.Current.Speak(textToSpeech, crossLocale: Helpers.Settings.CurrentLocale, cancelToken: ct);`

**Comment by jamesmontemagno** [comment]
@EmilAlipiev try 3.3.1 here in a few mins

**Comment by pollaris** [comment]
3.3.2 is working on android and windows phone now.  Thanks for your help.
