### ISSUE TITLE
The plugin always detects that TextToSpeech has not been initialized yet when calling GetInstalledLanguages() for the first time

### ISSUE THREAD

**Issue by ManhDucIT** [jamesmontemagno/TextToSpeechPlugin#47]
When calling GetInstalledLanguages() for the first time, the plugin always detects that the TextToSpeech has not been initialized yet leading to a wrong list of installed languages with a lot of languages which does not supported by TextToSpeech.

* Root cause:
   The "initialized = true;" line in OnInit() method is put bellow the line "initTcs.TrySetResult(true);".

* Solution:
   Re-order the two lines above.
   I have created a pull request to provide fixes for this issue. Please help me review and accept the merge   
   request.

## Bug Information

Version Number of Plugin:  v3.2.1
Device Tested On: Asus - Android OS 6.0
Simulator Tested On: Genymotion - Google Nexus 4.4.4
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by ManhDucIT** [comment]
Hi @jamesmontemagno,
Please upload new version of the plugin into nuget !

**Comment by jamesmontemagno** [comment]
I did already as a pre-release

**Comment by ManhDucIT** [comment]
Would you please upload it to release channel ?

**Comment by ManhDucIT** [comment]
Would you please upload it to release channel ?
