### ISSUE TITLE
Crash after upgrade to 3.1.1 and later with android

### ISSUE THREAD

**Issue by jdengg** [jamesmontemagno/TextToSpeechPlugin#49]
## Bug Information
from plugin verson 3.1.1 my app immediately crashes with unhandled exception
Plugin.Text To Speech.Abstractions.Text To Speech.Speak not found.

Version Number of Plugin: 3.1.1 and later
Device Tested On: Moto4 
Simulator Tested On: none
Version of VS: 2017 15.5.7 community
Version of Xamarin: 2.5.0.280555
Versions of other things you are using:
android 7.0
### Steps to reproduce the Behavior
see code snippet

### Expected Behavior
using version 3.0.1 is working fine

### Actual Behavior
Method is not entered. Excepction will not be caught, app crasshes completly

### Code snippet
button with simple method:
```csharp
        private async void StartAudio(object sender, System.EventArgs e)
        {
            try
            {
                await CrossTextToSpeech.Current.Speak("Test");
            }
            catch (Exception xxx)
            {
                await DisplayAlert("error", xxx.Message, "ok");
            }
        }
```

**Comment by prashantvc** [comment]
Could you share the crash log from the device? It will help us to troubleshoot the issue

**Comment by jamesmontemagno** [comment]
Probably need to completely clean all obj/bin and uninstall/reinstall nugets. Should work fine.
