### ISSUE TITLE
Error with TTS engine on progress listener

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/TextToSpeechPlugin#50]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
https://gist.github.com/EmilAlipiev/37cac6fa6c10ebdb1ad1cd5ecae75a98#file-gistfile1-txt

Version Number of Plugin: 3.3.2
Device Tested On: on different devices in production
Simulator Tested On: 
Version of VS: 2017 latest update
Version of Xamarin: 2.5.0.280555
Versions of other things you are using:

### Steps to reproduce the Behavior
Simple call like below
`     await Plugin.TextToSpeech.CrossTextToSpeech.Current.Speak(textToSpeech, crossLocale: Settings.CurrentLocale, cancelToken: ct);`
### Actual Behavior
 
I am seeing exceptions in my app center as in the link. Do you have any idea what could be the reason? I dont have any steps to reproduce as I only see in the exception logs on production for some devices. I logged information only if device has Supported and it is always IsSupported=true

**Comment by piterzet** [comment]
I have reached this error when deploying app on device which has WiFi turned off and no sim card inserted. Everything works fine when I turned on WiFi.
