### ISSUE TITLE
No sound when passed a string. Android Live Player.

### ISSUE THREAD

**Issue by Sammi3dev** [jamesmontemagno/TextToSpeechPlugin#55]
## Bug Information

Version Number of Plugin:
Device Tested On: Samsung SM-G925F Player
Version of VS: Community 2017 (15.6.1)
Version of Xamarin: 2.5.0.280555

### Steps to reproduce the Behavior
            CrossTextToSpeech.Current.Speak("Hello, I can speak.");
### Expected Behavior
Hear the words
### Actual Behavior
Silence
### Code snippet
            CrossTextToSpeech.Current.Speak("Hello, I can speak.");

**Comment by Sammi3dev** [comment]
Also, when I put the CrossTextToSpeech.Current.Speak method in a async method with an await before, the android live player app says Uncaught Exception Object of Type 'System.Double' does...

**Comment by Sammi3dev** [comment]
Anyone figured anything out?

**Comment by aritchie** [comment]
Await the speak call.  As for live player, it isn’t made for really anything beyond Xamarin forms design
