### ISSUE TITLE
After Dispose, TextToSpeech doesnt work

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/TextToSpeechPlugin#56]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: latest stable
Device Tested On:  UWP local
Simulator Tested On: Any Android Emulator
Version of VS: 2017
Version of Xamarin: 2.5
Versions of other things you are using:

### Steps to reproduce the Behavior
using the latest stable, If I use it as blow, it throws the attached exception, I am not sure if I am not supposed to use using,
### Expected Behavior
not to throw exception
### Actual Behavior

UWP:
https://gist.github.com/EmilAlipiev/dc443b20f442fc482c9750a4f7a2bdfa

Android:
https://gist.github.com/EmilAlipiev/ebcda35b693afe79b58c3d8d2383689b

### Code snippet

```

using (cts = new System.Threading.CancellationTokenSource())
                using (var current = Plugin.TextToSpeech.CrossTextToSpeech.Current)
                {
                    ct = cts.Token;
                    await current.Speak(textToSpeech, crossLocale: Helpers.Settings.CurrentLocale, cancelToken: ct);
                }
```

**Comment by EmilAlipiev** [comment]
it looks like my issue is related to https://github.com/jamesmontemagno/TextToSpeechPlugin/issues/40
I wonder if it is included in latest stable release or i should use some pre version?

**Comment by EmilAlipiev** [comment]
It seems like this issue https://github.com/jamesmontemagno/TextToSpeechPlugin/issues/50 is also related. I believe that once Dispose is called, it keeps throwing exception. 
In #40 stated that it is resolved but latest stable version still has the error. This is a big problem I am seeing if we cannot dispose the static object, it causes Cycles and memory leaks. even I am popping the page, it remains in the memory.

**Comment by jamesmontemagno** [comment]
This is the wrong implementation you are using to dispose:

```
using (cts = new System.Threading.CancellationTokenSource())
{
  var current = Plugin.TextToSpeech.CrossTextToSpeech.Current;
  ct = cts.Token;
  await current.Speak(textToSpeech, crossLocale: Helpers.Settings.CurrentLocale, cancelToken: ct);

  Plugin.TextToSpeect.CrossTextToSpeech.Dispose();
}
                
```

**Comment by EmilAlipiev** [comment]
ok, cool thank you. i was confused by #40

**Comment by EmilAlipiev** [comment]
hi @jamesmontemagno 

Regarding #50  is actually related to this problem even using your suggestion works perfectly fine on my android device. If I use emulator, it throws that exception. Emulator can be ignored but I have seen this exception on some devices on my production as you can see below. 2nd one is my emulator. 

![image](https://user-images.githubusercontent.com/10422347/38108241-7a31c866-3394-11e8-94d0-ac93f288be92.png)
