### ISSUE TITLE
iOS background Speak not speaking

### ISSUE THREAD

**Issue by nexxuno** [jamesmontemagno/TextToSpeechPlugin#58]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:3.3.2
Device Tested On: iphone 6, samsung s7
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: latest stable
Versions of other things you are using:

### Steps to reproduce the Behavior
Call ITextToSpeech.Speak from background

### Actual Behavior
In iOS it doesn't play anything even with "audio" set in background modes of info.plist. In android it works.

**Comment by jamesmontemagno** [comment]
This is not inherently supported on each platform and not supported officially by this library as AVSpeechSynthesizer does not support this out of the box.

You can get around it by using AVAudioPlayer and then using this library.
https://forums.developer.apple.com/thread/23160
