### ISSUE TITLE
This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation

### ISSUE THREAD

**Issue by joshivivek10** [jamesmontemagno/TextToSpeechPlugin#60]
Hi @jamesmontemagno 

I am getting following error while executing await CrossTextToSpeech.Current.Speak(text);. Am I missing anything?

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
  at Plugin.TextToSpeech.CrossTextToSpeech.get_Current () [0x00012]

**Comment by jamesmontemagno** [comment]
Please ensure that you install the package into your main applications for ios/android
