### ISSUE TITLE
CallBack if Text-to-Speech finished reading

### ISSUE THREAD

**Issue by Praveen19ojha** [jamesmontemagno/TextToSpeechPlugin#65]
Is there any callBack method which will inform us regarding the Text-to-speech has finished reading? or it is canceled?

**Comment by jamesmontemagno** [comment]
I would recommend using Xamarin.Essentials: https://docs.microsoft.com/en-us/xamarin/essentials/text-to-speech

When you "await" or "ContinueWith" then that is when it is done. There is also a cancellation token approach to cancel it easily.
